// lib/reports/storage.ts
// Generated report files live on disk in the config dir (they're binary and can
// be large), with metadata in the app_generated_reports table. Each file is
// named by an opaque key; the DB row maps key -> owner + display name so
// downloads can be authorized and named nicely.
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

const CONFIG_DIR = process.env.APP_CONFIG_DIR
  ? path.resolve(process.env.APP_CONFIG_DIR)
  : path.join(process.cwd(), "data");
const REPORTS_DIR = path.join(CONFIG_DIR, "reports");

/** A safe, unique on-disk file name for a generated report. */
export function newFileKey(format: string): string {
  return `${randomUUID()}.${format}`;
}

export function writeReportFile(fileKey: string, data: Buffer): void {
  if (!existsSync(REPORTS_DIR)) mkdirSync(REPORTS_DIR, { recursive: true });
  // fileKey is generated by newFileKey (a UUID + ext) — never client-supplied.
  writeFileSync(path.join(REPORTS_DIR, fileKey), data);
}

/** Read a stored report file. Returns null if it's missing (e.g. purged). */
export function readReportFile(fileKey: string): Buffer | null {
  // Guard against traversal even though keys are server-generated.
  if (fileKey.includes("/") || fileKey.includes("\\") || fileKey.includes("..")) return null;
  const p = path.join(REPORTS_DIR, fileKey);
  return existsSync(p) ? readFileSync(p) : null;
}

export function deleteReportFile(fileKey: string): void {
  if (fileKey.includes("/") || fileKey.includes("\\") || fileKey.includes("..")) return;
  const p = path.join(REPORTS_DIR, fileKey);
  if (existsSync(p)) rmSync(p, { force: true });
}
